DROP TABLE IF EXISTS departments;
CREATE TABLE departments(
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
	title VARCHAR(50) NOT NULL,
	description TEXT DEFAULT '',
	create_timestamp TIMESTAMP DEFAULT 0,
	update_timestamp TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS tickets;
CREATE TABLE tickets(
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	staff_id INT(11) UNSIGNED DEFAULT 0,
	user_id INT(11) UNSIGNED DEFAULT 0,
	created_by ENUM('staff','user') NOT NULL,
	create_timestamp TIMESTAMP DEFAULT 0,
	update_timestamp TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	
	department_id INT(11) UNSIGNED NOT NULL,
	FOREIGN KEY(department_id) REFRENCES departments(id)  
);

DROP TABLE IF EXISTS ticket_post;
CREATE TABLE ticket_post(
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ticket_id INT(11) UNSIGNED NOT NULL,
	content TEXT,
	create_timestamp TIMESTAMP DEFAULT 0,
	update_timestamp TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	
	FOREIGN KEY(ticket_id) REFRENCES tickets(id)
);

DROP TABLE IF EXISTS units;
CREATE TABLE units(
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(100),
	create_timestamp TIMESTAMP DEFAULT 0,
	update_timestamp TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	
)

DROP TABLE IF EXISTS staff;
CREATE TABLE staff(
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100),
	create_timestamp TIMESTAMP DEFAULT 0,
	update_timestamp TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	
);

DROP TABLE IF EXISTS user;
CREATE TABLE user(
	id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100),
	email_id TEXT,
	create_timestamp TIMESTAMP DEFAULT 0,
	update_timestamp TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	
);